/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface InlineEditor {
        "code": string;
        /**
          * This is a hack. I can't get the cursor to behave so I just exposed this.
         */
        "forceCodeChange": (code: string) => Promise<void>;
    }
    interface InlineRenderLogs {
        "logs": { level: string; message: string }[];
    }
    interface InlineRoot {
    }
}
declare global {
    interface HTMLInlineEditorElement extends Components.InlineEditor, HTMLStencilElement {
    }
    var HTMLInlineEditorElement: {
        prototype: HTMLInlineEditorElement;
        new (): HTMLInlineEditorElement;
    };
    interface HTMLInlineRenderLogsElement extends Components.InlineRenderLogs, HTMLStencilElement {
    }
    var HTMLInlineRenderLogsElement: {
        prototype: HTMLInlineRenderLogsElement;
        new (): HTMLInlineRenderLogsElement;
    };
    interface HTMLInlineRootElement extends Components.InlineRoot, HTMLStencilElement {
    }
    var HTMLInlineRootElement: {
        prototype: HTMLInlineRootElement;
        new (): HTMLInlineRootElement;
    };
    interface HTMLElementTagNameMap {
        "inline-editor": HTMLInlineEditorElement;
        "inline-render-logs": HTMLInlineRenderLogsElement;
        "inline-root": HTMLInlineRootElement;
    }
}
declare namespace LocalJSX {
    interface InlineEditor {
        "code"?: string;
        "onCodeChanged"?: (event: CustomEvent<string>) => void;
    }
    interface InlineRenderLogs {
        "logs"?: { level: string; message: string }[];
    }
    interface InlineRoot {
    }
    interface IntrinsicElements {
        "inline-editor": InlineEditor;
        "inline-render-logs": InlineRenderLogs;
        "inline-root": InlineRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "inline-editor": LocalJSX.InlineEditor & JSXBase.HTMLAttributes<HTMLInlineEditorElement>;
            "inline-render-logs": LocalJSX.InlineRenderLogs & JSXBase.HTMLAttributes<HTMLInlineRenderLogsElement>;
            "inline-root": LocalJSX.InlineRoot & JSXBase.HTMLAttributes<HTMLInlineRootElement>;
        }
    }
}
