/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults } from "@stencil/router";
export namespace Components {
    interface AppHome {
    }
    interface AppProfile {
        "match": MatchResults;
    }
    interface AppRoot {
    }
    interface InlineEditor {
        "code": string;
    }
    interface InlineRenderLogs {
        "logs": { level: string; message: string }[];
    }
    interface InlineRoot {
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLInlineEditorElement extends Components.InlineEditor, HTMLStencilElement {
    }
    var HTMLInlineEditorElement: {
        prototype: HTMLInlineEditorElement;
        new (): HTMLInlineEditorElement;
    };
    interface HTMLInlineRenderLogsElement extends Components.InlineRenderLogs, HTMLStencilElement {
    }
    var HTMLInlineRenderLogsElement: {
        prototype: HTMLInlineRenderLogsElement;
        new (): HTMLInlineRenderLogsElement;
    };
    interface HTMLInlineRootElement extends Components.InlineRoot, HTMLStencilElement {
    }
    var HTMLInlineRootElement: {
        prototype: HTMLInlineRootElement;
        new (): HTMLInlineRootElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "inline-editor": HTMLInlineEditorElement;
        "inline-render-logs": HTMLInlineRenderLogsElement;
        "inline-root": HTMLInlineRootElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppProfile {
        "match"?: MatchResults;
    }
    interface AppRoot {
    }
    interface InlineEditor {
        "code"?: string;
        "onCodeChanged"?: (event: CustomEvent<string>) => void;
    }
    interface InlineRenderLogs {
        "logs"?: { level: string; message: string }[];
    }
    interface InlineRoot {
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "inline-editor": InlineEditor;
        "inline-render-logs": InlineRenderLogs;
        "inline-root": InlineRoot;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "inline-editor": LocalJSX.InlineEditor & JSXBase.HTMLAttributes<HTMLInlineEditorElement>;
            "inline-render-logs": LocalJSX.InlineRenderLogs & JSXBase.HTMLAttributes<HTMLInlineRenderLogsElement>;
            "inline-root": LocalJSX.InlineRoot & JSXBase.HTMLAttributes<HTMLInlineRootElement>;
        }
    }
}
